M48
; DRILL file {KiCad 9.0.2} date 2025-06-10T22:08:11+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-10T22:08:11+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X169.5Y-130.92
X169.5Y-141.08
T2
X154.5Y-134.0
X154.5Y-136.54
M30
