M48
; DRILL file {KiCad 9.0.2} date 2025-06-05T19:52:53+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-05T19:52:53+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X180.5Y-106.5
X191.0Y-115.5
T2
X179.0Y-109.96
X179.0Y-112.5
M30
